=== JesusSosaMorales/Jesus_LND/TRIMESTRE 2/UD5/DOSSIER/Practica4/practica4.dtd
<!-- DTD created at Fri Mar 12 11:41:21 GMT 2021 with EditiX. Please insert an encoding attribute header for converting any DTD  -->


<!ELEMENT libreria (libros)+>
<!ELEMENT libros (autor,titulo,editorial)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>

=== JesusSosaMorales/Jesus_LND/TRIMESTRE 2/UD5/DOSSIER/Practica4/Practica4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE libreria SYSTEM "practica4.dtd">


<libreria>
	<libros>
		<autor>Miguel de Cervantes</autor>
		<titulo>Don Quijote de La Mancha</titulo>
		<editorial/>
	</libros>
	<libros>
		<autor>Karlos Argui√±ano</autor>
		<titulo>Cocina Dia a Dia</titulo>
		<editorial>Planeta</editorial>
	</libros>
	<libros>
		<autor>Miguel Angel Acera</autor>
		<titulo>C/C++</titulo>
		<editorial>Anaya</editorial>
	</libros>
	<libros>
		<autor>Alexander Cane</autor>
		<titulo>Programa en Phytom</titulo>
		<editorial>Amazon</editorial>
	</libros>
</libreria>
